// <auto-generated />
namespace DSCodeFirst.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class hop1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hop1));
        
        string IMigrationMetadata.Id
        {
            get { return "201911141503548_hop1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
